# Generated by Django 5.0.1 on 2024-02-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='articles_img/')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(choices=[(0, 'draft'), (1, 'published')], default=0)),
                ('views_amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('-create_date',),
            },
        ),
    ]
